FROM node:18.14.2-alpine
# 18.14.2-slim
CMD mkdir /project
COPY ../client/ /project/client
COPY ../package.json /project/package.json

WORKDIR /project
RUN npm install

WORKDIR /project/client/
RUN npm install
RUN chmod +x node_modules/.bin/react-scripts

CMD ["npm","start"]