FROM node:18.14.2-alpine
# 18.14.2-slim
RUN mkdir /client
COPY . /client

WORKDIR /client
# 處理react.env的參數
ENV REACT_APP_BACKEND_URI=$REACT_APP_BACKEND_URI
ENV REACT_APP_CKAN_TOKEN=$REACT_APP_CKAN_TOKEN

RUN npm install
RUN chmod +x node_modules/.bin/react-scripts
CMD ["npm","start"]
